### ISSUE TITLE
Access Datanodes from scenarios/pipelines

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#181]
**What would that feature address**
The goal would be able to access Data Nodes directly through pipelines/scenarios. To do that, we need to use `tp.get_data_nodes()` and then filter on scenarios and pipelines. Adding a new API, it would help the user access easily the Data Nodes he created for his scenario/pipeline.

***Description of the ideal solution***
The ideal solution is to have a new API on the same format as pipelines. `<scenario>.datanodes` should return a dictionary with the id of Data Nodes and the objects (same thing for `<scenario>.<pipeline>.datanodes` )

***Caveats***

***Other options***

**Comment by jrobinAV** [comment]
@toan-quach Before to close the ticket, can you add:
- Some user manual documentation about this new API
- A new entry in the release notes for core 

Thx
