### ISSUE TITLE
BUG-self_setter not received token params

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy-core#216]
**Description**
In the self_setter function (and maybe also reload function) of `common/_reload.py`, token was not passed. Therefore, when authentication is enabled, it will return error token not found.

**Expected behavior**
A way to inject the token to the function for user validation

**Runtime environment**
Please specify relevant indications.
 - Taipy version:
 - OS: [e.g. Linux, Windows] and version
and any other relevant information.

**Comment by jrobinAV** [comment]
Ticket #25 of taipy-auth should resolve this ticket.
