### ISSUE TITLE
Run Core as a service

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#275]
### Description : 
The purpose is keep the decoupling between the scheduler from the dispatcher. The final target is to only have the queue in common.

This ticket is about starting the Dispatcher of taipy-core independently from the scheduler Factory. For that we propose to create a Core class as a runnable (similar to Rest or Gui class).

Two alternatives have been evaluated : Running Core as a Flask application or Running Core as a Thread. 
Today taipy.run() can run a common Flask application for both Gui() and Rest(). We can include Core as well, in anticipation of a future need, but it is not mandatory for this ticket.

`standalone`  mode:
The dispatcher must be started through taipy.run(Core()). It runs a Standalone dispatcher in a dedicated thread. The submit execution flow just adds some jobs in the queue and is fully independent of the dispatcher flow. The dispatcher loops forever and pop jobs from the queue to execute them.

`development` mode :
When taipy.run(Core()) is called in a development mode, the DevelopmentDispatcher.start method should do nothing. In a `development` mode ONLY, after submitting a job, a DevelopmentJobDispatcher is instantiated and executes the current job in a synchronous mode (no parallelism). After the job is completed, the development dispatcher can be deleted.

### acceptance criteria :

- [ ] Create a Core class to be run within taipy.run(). the Core.run method should call the call the start method of the dispatcher.
- [x] Separate the development dispatcher from the standalone dispatcher. Indeed, the development dispatcher does not benefit from inheriting from the standalone dispatcher. It should directly inherit from JobDispatcher and re-implement a dedicated dispatch method.
- [x] Ensure standalone and development dispatcher are well tested with unit tests
- [ ] Update old milestone to demonstrate both standalone and development modes are working.
- [ ] Update documentations
- [ ] Update release notes for 1.2

**Comment by toan-quach** [comment]
Note:

In Core class:
- The __init__ method can be used to create a scheduler object that will be passed to the dispatcher class (the dispatcher needs the queue from the scheduler)
- We can also consider calling _build_dispatcher in run function to both create the dispatcher and start it
