### ISSUE TITLE
Create a synchronous submit method in the scheduler

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#276]
In development mode, the synchronous submit should do the same as the submit method.
In standalone mode, the synchronous submit should block until all the submitted jobs are finished (completed, failed, abandoned, or canceled)

**Comment by toan-quach** [comment]
@jrobinAV I believe this ticket has already been implemented in the current version of scheduler and dispatcher. We can improve it by some further refactoring between development mode and standalone mode. But the general idea is already there

**Comment by jrobinAV** [comment]
Not really, in standalone mode, the submit is always asynchronous. I would like to have a synchronous_submit method. It could simply delegate the submission to the usual asynchronous way, and wait for all jobs to be finished before to return.

**Comment by toan-quach** [comment]
Ah I see what you mean. So we will have another synchronous_submit but for standalone mode where it will wait for all the submitted jobs to be finished before actually do the returning

**Comment by jrobinAV** [comment]
Yes. absolutely

**Comment by jrobinAV** [comment]
An alternative to the new method could also be to reuse the same submit method. It could take a new `sync` boolean parameter with a default value equals to False (asynchronous). When we set the parameter to True, it becomes synchronous.
