### ISSUE TITLE
Prevent canceling finished jobs

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy-core#283]
**Description**
Cancel job feature is currently set to cancel all jobs despite its status aside from RUNNING. We should prevent job cancelation for jobs that have status COMPLETED, CANCELED, SKIPPED, ABANDONED, FAILED. 
In other words, we should only cancel jobs with the status SUBMITTED, PENDING, and BLOCKED.

What to do:

- [x] Update the cancel job feature to make sure it cancels jobs with the right status and log when the status is incorrect (as listed above)
- [x] Make sure the new code is tested carefully
- [x] Update the doc to reflect the changes in the job cancelation feature

**Comment by jrobinAV** [comment]
@toan-quach side remark. I believe the message to log should be an info message. A warning would be too strong. What do you think? 
Besides the log, canceling a COMPLETED job should still trigger the abandonment of the subsequent jobs. Do you agree?

**Comment by toan-quach** [comment]
@jrobinAV 
- I chose warning to illustrate it might have a different behavior compared to what the user might expect. Info log makes sense to me too. I'll go with info then :D 
- To abandon the subsequent jobs of the completed job -> It make senses to me. Then what about SKIPPED? Since FAILED, CANCELED and ABANDONED should prevent the subsequent jobs from running already, but we cant say the same for SKIPPED right?

**Comment by jrobinAV** [comment]
Right!

For skipped, I believe we should abandon the subsequent jobs as well.

**Comment by toan-quach** [comment]
Update:
Log level to be used will be info (for all job status including the change of warning level for running jobs atm)
