### ISSUE TITLE
Overwrite data in SQLDataNode

### ISSUE THREAD

**Issue by khaitruong922** [Avaiga/taipy-core#294]
Currently, when writing into a SQLDataNode, it only executes INSERT operation, which add data without overwriting existing data. This behavior makes it inconsistent with other data nodes and produces output data that does not match the input size if the table already has some data. We should change the default behavior to clear all rows in the table before inserting, and keep the old behavior if there is any use case to it.

**Comment by jrobinAV** [comment]
@khaitruong922 

To make it completely consistent, we also need to be able to retrieve the written data when reading the data node.

In other words : 
```
written_data = [{"first":  1, "second": 2}, {"first":  3, "second": 4}]
data_node.write(written_data)
read_data = data_node.read()
assert written_data == read_data
``` 

**Solution proposed:**
So for a dataset in a single table, we want to have a SQLTableDataNode that just take the table_name as parameter (in the config). and Taipy can execute simple reading query : `SELECT * FROM {table_name}` and writting query : `DROP TABLE table_name; INSERT INTO {table_name} VALUES ({data})`  

For more complex dataset (stored in multiple tables with join) we want to have a SQLDataNode that takes as parameter (in the config) the reading query template, the reading args, the writting query template, the writting args (you can have a look at the genericDataNode which have a similar behavior).
