### ISSUE TITLE
[BUG] ExcelDataNode - Read sheet names on demand

### ISSUE THREAD

**Issue by khaitruong922** [Avaiga/taipy-core#303]
In the current version, if we provide a custom class for `exposed_type` property in ExcelDataNode, it will try to read the sheet name immediately to compute the dictionary with sheet name maps to that exposed_type, which may cause error if the file is not created yet. Another problem with converting the exposed type to dictionary is that when the path is changed, the other file may have different set of sheet names. Since the `exposed_type` is now a dictionary, it is not recomputed again, so it is still the dictionary with old sheet names.

Here is some proposed solutions to fix this.
1. Do not try to read the sheet names before the data node is read.
2. Preserve the information that the exposed type is initially provided as a dictionary or custom class instead of converting the custom class into a dictionary.

**Comment by jrobinAV** [comment]
Well spotted! Thanks.
