### ISSUE TITLE
Ability to export the local files of a single scenario

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#307]
**What would that feature address**
This feature would enable the user to export all the files needed for a scenario without exporting all the .data. Sometimes, just one or a small group of scenarios need to be exported.

***Description of the ideal solution***
A Python line of code and/or an API Rest command line should be able to give all the files of the local system concerning a scenario

***Proposal***
Having a Python command to export a scenario : `taipy.export("folder_name", "scenario_id")`

The result would be the following folder hierarchy:
```
folder_name
   - cycles
        - cycle_id.json
   - datanodes
        - datanode_id1.json
        - datanode_id2.json
        ...
   - jobs
        - job_id1.json
        - job_id2.json
        - job_id3.json
        ...
   - pipelines
        - pipeline_id1.json
        - pipeline_id2.json
   - scenarios
        scenario_id.json
   - tasks
        - task_id1.json
        - task_id2.json
```

When the folder_name already exists, the call of `taipy.export()` should delete the folder before recreating it.

**Comment by jrobinAV** [comment]
@FlorianJacta Do we want to export pickle files as well ? I would say no! Do you agree?

Answer is no

**Comment by jrobinAV** [comment]
If a MongoRepository or an SQLRepository is used, we still want to export the scenario as JSON files. This should be part of another ticket.
