### ISSUE TITLE
Add support for other SQL engines to SQLDataNode

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#319]
Currently on taipy 1.1.0, only MSSQL and SQLLite are supported by SQLDataNodes.
We can add support for more SQL:
- [ ] mysql using https://pypi.org/project/PyMySQL/
- [ ] postgreSQL using https://www.psycopg.org/

**Comment by jrobinAV** [comment]
Good idea! 
I move it to the Product backlog, 'cause it's a perfect ticket to take when we are early in a sprint.
