### ISSUE TITLE
Ability to create multiple instance of taipy-core application

### ISSUE THREAD

**Issue by tsuu2092** [Avaiga/taipy-core#32]
This is just my suggestion on taipy-core architecture and I would like this to be discussed in the next sprint planning as this is a breaking change.

Suppose I want to build two applications in one project: one for predicting weather and one for predicting stock prices.

Currently, since we only have one global config which is a singleton, which means every entities will share the same environment with others, regardless of relatedness.

```
Config.add_scenario([predict_weather_pipeline])
Config.add_scenario([predict_stock_pipeline])
```

In the above example, all the data nodes, tasks, pipelines and scenarios of weather and stock will be saved in the same folder, even though they are never used with each other.

What I propose is that we should allow user to create multiple instance of Taipy application (or Config). For example:

```
weather_app = Config()
weather_app.add_scenario([predict_weather_pipeline])

stock_app = Config()
stock_app.add_scenario([predict_stock_pipeline])
```

In the above example, since there are two different configs, we cannot access stock-related entities from the weather app (which is a good thing).

Even though the use case of having two different applications in the same project is not common, I think this issue should be discussed to see if it is useful enough to be refactored into.

**Comment by jrobinAV** [comment]
REJECTED
