### ISSUE TITLE
Update Datanode cache when file is written (or update)

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#337]
- [x] For Datanodes associated with a file, the cache can also use the last edit timestamp of the file to check if the data node is up-to-date or not. The concerned data nodes are Excel, CSV, JSON, and Pickle, (maybe SQLlite?, SQLTable?, MongoCollection?)
- [x] Unit tests
- [x] Documentation
- [x] end2end demo

**Comment by toan-quach** [comment]
@jrobinAV 
It seems like SQLite and Mongodb don't support storing "last modified date" at the moment. If we want to use something like that, we will need to implement it ourselves. :D

**Comment by jrobinAV** [comment]
> @jrobinAV It seems like SQLite and Mongodb don't support storing "last modified date" at the moment. If we want to use something like that, we will need to implement it ourselves. :D

OK let s postpone that for now. Thx!
