### ISSUE TITLE
Missing tooltips in IDE when using Config class for configuring data nodes

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-core#348]
**Description**
In Taipy 2.0, I noticed that methods such as `configure_data_node` are assigned to the `Config` class in `taipy.core.config.__init__.py`, rather than originally being in the class definition.

A side effect of this change appears to be that tooltips // type hints are no longer showing up for me when I use `Config.configure_data_node` in my IDE. I'm using VS Code with Pylance.

**Comment by jrobinAV** [comment]
Hello, 

Thank you for the issue. 

Indeed, we noticed this side effect of the config refactoring. As a workaround, you can still refer to the reference manual documentation. We consider this issue very important, so I believe we will engage it in our next development sprint to find a solution as soon as possible.

Thank you again.

**Comment by Dr-Irv** [comment]
Dynamic injection is not good for providing type hints.

You could provide `pyi` files that include the documentation and then the tool tips would work.  You also get the benefit of type checking as well.

For example, if I place a file called `config.pyi` in `taipy/config` in the installed version, that looks like:
```python
class Config:
    @staticmethod
    # Copied from ./core/config/data_node_config.py:_configure
    def configure_data_node(
        id: str,
        storage_type: str = ...,
        scope: Scope = ...,
        cacheable: bool = ...,
        **properties : Any,
    ):
       """
       This is some docs
       """
```

Then in VS Code, I see the following when I hover over `configure_data_node`.  You'd have to do some work to auto-generate the pyi file with the corresponding docs from the source.

![image](https://user-images.githubusercontent.com/15113894/197877110-3c4f5f63-9af1-4c45-96e1-559536b13c46.png)

**Comment by jrobinAV** [comment]
A first version will be merged soon on develop branch. In this first version a `config.pyi` file is directly added to `taipy/config` folder in taipy-config repository.

However, this is not great since this creates a dependency of taipy-config on taipy-core. A better implementation is planned later so the `config.pyi` file is autoùmatically generated. 

This is the corresponding [issue](https://github.com/Avaiga/taipy/issues/77).
