### ISSUE TITLE
Create versioning module

### ISSUE THREAD

**Issue by joaoandre-avaiga** [Avaiga/taipy-core#352]
### Description

Create a versioning module for taipy. The module must be able to:
  - Create and Load a version of a config
  - Store the versions onto a storage system

Please follow the following naming convention [here](https://docs.google.com/document/d/1vOuXbJKHxvY2Ee2UPkruWgYhVW6YHthbnkqnmuoN4zE/edit#)

**Comment by jrobinAV** [comment]
https://docs.google.com/document/d/1vOuXbJKHxvY2Ee2UPkruWgYhVW6YHthbnkqnmuoN4zE/edit#
