### ISSUE TITLE
Dev mode : Modify the `_load_all` and `load_all_by` to take a version number into account

### ISSUE THREAD

**Issue by joaoandre-avaiga** [Avaiga/taipy-core#355]
### Description

Change the repository APIs `_load_all` and `load_all_by` to list only the entities related to a version.

- Make sure to modify the manager APIs if necessary
- By default, the current version should be used
- Evaluate new performances in integration-testing repository

**Comment by trgiangdo** [comment]
- Extend the behavior of `--experiment` mode as the current `--production` mode
- Change the `--production` mode behavior to be able to load entities from older production version.
