### ISSUE TITLE
Create a json schema representing the description of the Config sections

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#365]
- Create a JSON schema representing the various Config sections.
- The file should be in src/taipy/core/config

JSON schema documentation: https://json-schema.org/
Example of schema: https://github.com/Avaiga/taipy-studio/blob/develop/core/schemas/config.schema.json

**Comment by toan-quach** [comment]
@jrobinAV 

1. Is the idea of this ticket to create a static JSON schema to represent the Config sections and store it in taipy core? 
2. The schema style is pretty clear from the file in taipy studio, can I just follow this file and make one for taipy core? 
3. Should this file be generated manually or do we have a way to create it automatically?
4. Also do we need an api/function to expose this in the code?

**Comment by jrobinAV** [comment]
1. yes
2. yes. But please make sure it is up to date regarding the recent changes (modin, parquet, and so on)
3. I believe it can remain manual.
4. No need for that.
