### ISSUE TITLE
Implement Config comparator to compare between versions

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#381]
**Description**

The purpose is to compare between the Python Config and the Config from an older version when run on `--experiment` mode.

If there is any difference, the comparator API should be able to specify where the difference come from in Python Config so that the user can update it accordingly.

**Comment by jrobinAV** [comment]
Should the comparator be implemented in taipy-config repository ?

**Comment by trgiangdo** [comment]
Yes we can.

We just need to serialize the Python Config and call the comparator from taipy-config to do the job.

**Comment by trgiangdo** [comment]
@jrobinAV I'll delete this ticket and create a new one on taipy-config if that's ok to you.

**Comment by trgiangdo** [comment]
Moved to https://github.com/Avaiga/taipy-config/issues/27
