### ISSUE TITLE
Design data migration API for the Versioning system

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#385]
**Description**

The purpose of data migration API is to help user migrate from an older production version to newer one.

**Example**

- The user had a Taipy application running on production mode in January, named version "jan2022".
- In Feb, the user created a new stable version named "feb2022" and wants to push this to production.
- However, the entities from "jan2022" have different properties compared to "feb2022" (for example, `cacheable` property of a data node is updated to `True`).
- By using the new API, the user can detect and update old entities accordingly to avoid conflict on production environment.

**Expected solution**

- [x] Propose an RFC document with a code design to allow dev-users to pass migration functions to Taipy core.

**Comment by florian-vuillemot** [comment]
To split !

**Comment by trgiangdo** [comment]
Documentation for the API: https://docs.google.com/document/d/14bvCtGgaz8T1Oml_yDVh2SD97KwcDwLxzjl6UtmNm6U
