### ISSUE TITLE
Change "override" to delete existing config and new option "force" to replace "override" for versioning

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#412]
**Description**
It is a proposal to:
- Make an option 'force' that will have the same role as the current _override_. (an remove the override)
- Make an option 'clean-entities' that deletes entities of the provided version.
- Change the -h documentation

**Comment by trgiangdo** [comment]
I agree with the `--force` or `-f` option to override a version.

About the delete entities when override, how about production version?

@jrobinAV what do you think?

**Comment by jrobinAV** [comment]
- About the force option: I prefer the term --force over --override.
- About deleting entities for experiment mode: 
I believe it is a very advanced usage to override data on experiment mode. I am not sure to well understand the use case, to be honest. You have a stable experiment version 1.0 with some data. You want to run the application again with version 1.0, but you want to delete previous data. What could be the reason? You are not in dev mode anymore. If you want to remove the data associated with an experiment version, you can just delete the version directly before running the application again.
- About the production mode:
I would not accept `override` in production mode. It is too dangerous for me. Maybe not even the or `force` parameter.

**Comment by trgiangdo** [comment]
- In **experiment** mode: I agree the user can run `--delete-version` to clean that version before create a new experiment version. However, when thinking of override an old version, it means to override everything, even older entities, so it kinda make sense.

- In **production**: If the user can not `--force`, then there will be no other way to run 2 incompatible versions rather than delete the old one, until a data migration API is introduced.

**Comment by jrobinAV** [comment]
In production, the data must be migrated. Indeed. It does not really require taipy for that. But opening a migration API would definitely help the user !!

**Comment by jrobinAV** [comment]
After discussion, here is what we want : 

- a `--force` parameter that updates the config of the current version before running the app, even if there are some differences.
- a `--clean-entities` parameter that removes all the entities of the current version before running the app , even if there are some differences.  

The two parameters are fully independent, meaning we can use one with or without the other.
The two parameters are usable whatever the mode.
