### ISSUE TITLE
BUG-Problem of formatting for version number

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#414]
**Description**

When listing versions, the name of versions are not correctly formatted.

Make sure that works in a Notebook environment as well.

**How to reproduce**

Create a version (dev/exp/prod).

Use:
```
python main.py -l
```

**Expected behavior**

The names of versions should be correctly formatted.

**Screenshots**

![Capture d’écran 2023-01-09 094040](https://user-images.githubusercontent.com/98709993/211268547-b2d37786-cb5a-4e5e-bde0-6ba5f7f34a27.png)

**Runtime environment**
Taipy Core: develop

**Comment by trgiangdo** [comment]
Hi @FlorianJacta, is it Powershell in your screenshot?

**Comment by FlorianJacta** [comment]
It is Anaconda prompt

**Comment by trgiangdo** [comment]
The issue comes from color printing in Python and it is not working at some terminal I suppose. 

I'll see what I can do about this.

**Comment by trgiangdo** [comment]
TODO: Check if the terminal support ANSI escape codes or not, if yes then applied the color format.

Possible solution: https://stackoverflow.com/questions/7445658/how-to-detect-if-the-console-does-support-ansi-escape-codes-in-python

**Comment by jrobinAV** [comment]
We need to test the solution on notebooks as well.
