### ISSUE TITLE
Remove Type ignore from DataNode.storageType() method

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#417]
The storageType method must return a str and not an Optional[str]. This is incompatible with the current implementation of the `_class_map` method

**Comment by ashutuptiwari** [comment]
I am assuming you're referring to this method 
![image](https://github.com/Avaiga/taipy-core/assets/106370097/ba707ddc-e29d-47e5-9458-596053e4881d)
in the file src/taipy/core/data/data_node.py. 
Can you explain the changes that are needed and assign this issue to me
@jrobinAV

**Comment by trgiangdo** [comment]
If you remove the `# type: ignore`, mypy will complain that:
```
Incompatible return value type (got "Type[NotImplementedError]", expected "str")
```

The purpose of this issue is to safely remove the `# type: ignore` and still follow mypy style guideline.

**Comment by ashutuptiwari** [comment]
Alright I'll get started @trgiangdo . Please assign this issue to me @jrobinAV

**Comment by ashutuptiwari** [comment]
> If you remove the `# type: ignore`, mypy will complain that:
> 
> ```
> Incompatible return value type (got "Type[NotImplementedError]", expected "str")
> ```
> 
> The purpose of this issue is to safely remove the `# type: ignore` and still follow mypy style guideline.

What command is leading to this error log? @trgiangdo

**Comment by trgiangdo** [comment]
You can try to remove the `# type: ignore` and run this command on the terminal:
```
mypy --ignore-missing-imports --implicit-optional .
```

**Comment by ashutuptiwari** [comment]
Thanks!

**Comment by ashutuptiwari** [comment]
i got this error 2 times , but not the one that you mentioned
```
 error: No overload variant of "asdict" matches argument type "_BaseModel"  [call-overload]
```
@trgiangdo

**Comment by trgiangdo** [comment]
The full error message that you are looking for:
```
src/taipy/core/data/data_node.py:314: error: Incompatible return value type (got "Type[NotImplementedError]", expected "str")  [return-value]
```

If it's not showing up, maybe we are missing something.

**Comment by ashutuptiwari** [comment]
Yeah that one isn't there 
![image](https://github.com/Avaiga/taipy-core/assets/106370097/fd337916-17ca-49e9-8b02-f2b9f90455df)
@trgiangdo

**Comment by ashutuptiwari** [comment]
@trgiangdo ?

**Comment by trgiangdo** [comment]
Can you show me:
- The Python version
- The mypy version
- The screenshot of the `src/taipy/core/data/data_node.py` file at line 311-314

**Comment by ashutuptiwari** [comment]
Sure, what command should i use for python @trgiangdo ?
The mypy version is giving the same result as before
Here is the ss of the code you asked for
![image](https://github.com/Avaiga/taipy-core/assets/106370097/4e73bba9-1315-4464-a8e1-d65f273f55b9)

**Comment by trgiangdo** [comment]
Can you try to remove the `# type: ignore` from line 314?
Then the error I mentioned should show up.

**Comment by ashutuptiwari** [comment]
![image](https://github.com/Avaiga/taipy-core/assets/106370097/a89f5949-a134-4d59-a910-a606a298b25c)
This seems to solve the issue. This along with adding a attribute __STORAGE_TYPE="DataNode"
@trgiangdo

**Comment by ashutuptiwari** [comment]
Also, thanks for the fast replies .Legit the fastest and the most helpful I've yet encountered. @trgiangdo

**Comment by ashutuptiwari** [comment]
Both these solution seem to resolve this error @trgiangdo 

1. 
![image](https://github.com/Avaiga/taipy-core/assets/106370097/51955fbb-ff7d-44b7-a03f-9369c21149eb)

2.
![image](https://github.com/Avaiga/taipy-core/assets/106370097/02441eb1-7402-404a-bc3d-cbe21996d677)

**Comment by ashutuptiwari** [comment]
Also thanks for the fast replies. Definitely the fastest and the most helpful I've yet encountered.

**Comment by ashutuptiwari** [comment]
@trgiangdo

**Comment by trgiangdo** [comment]
Sorry for the late response, I was away for the weekend.

About your fix, it's contradictory with the purpose of the storage_type() method.
It should always return the NotImplemented exception to avoid the user from using the _DataNode class directly, or a child class without the storage type would raise an error.

Please find another work-around

**Comment by ashutuptiwari** [comment]
![image](https://github.com/Avaiga/taipy-core/assets/106370097/a533c3f0-8635-4bf5-8ea4-c1c426d91fed)
This seems to work as well @trgiangdo

**Comment by ashutuptiwari** [comment]
Hacktoberfest will be ending tomorrow so it will be really helpful if we could close this issue before then @trgiangdo . Please review this solution

**Comment by ashutuptiwari** [comment]
Hey, i think there has been some mistake 
![image](https://github.com/Avaiga/taipy-core/assets/106370097/d94ce65b-d33a-4760-9dea-37238c27a797)
because this repository is shown as **not participating** in hacktoberfest 2023.
Please look into it. 
@trgiangdo @jrobinAV @FlorianJacta

**Comment by ashutuptiwari** [comment]
![IMG-20231030-WA0045.jpg](https://github.com/Avaiga/taipy-core/assets/106370097/409a3dd0-14c3-477a-b968-962fe43e6260)


Please confirm @trgiangdo

**Comment by FlorianJacta** [comment]
@ashutuptiwari The warning should go away now. Can you try again?

**Comment by ashutuptiwari** [comment]
Yes it did @FlorianJacta . Thanks a  bunch!

**Comment by ashutuptiwari** [comment]
I guess this issue can be closed?

**Comment by trgiangdo** [comment]
We will review it and close done issue on every sprint. The merged PR should be sufficient for the hacktoberfest, no?

**Comment by ashutuptiwari** [comment]
Oh yes it is. I was just curious.

**Comment by ashutuptiwari** [comment]
Hi guys, I was wondering if i would recieve some sticker packs or some swag 
![image](https://github.com/Avaiga/taipy-core/assets/106370097/5b3a89fb-07b8-413f-95a4-08d5dcbe61c8)
@FabienLelaquais @jrobinAV @FlorianJacta @marisogo

**Comment by marisogo** [comment]
Hi @ashutuptiwari, can you shoot me an email at: marine.gosselin@taipy.com? So we can organize sending you the swag :)
