### ISSUE TITLE
remove unused parameters

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#441]
Remove unused parameters on DataManager: 
- _bulk_get_or_create -> Task_id 
- _create_and_set -> parent_ids 
- __create -> parent_ids

**Comment by trgiangdo** [comment]
Hi @jrobinAV, the `parent_ids` parameter in `_create_and_set()` and `__create()` methods are actually used to init the DataNode object.

Did I miss something?

**Comment by jrobinAV** [comment]
I am probably mistaken...
