### ISSUE TITLE
New API to create Global Data Nodes

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#449]
**What would that feature address**
Creating Global Data Nodes and using them in a Taipy Core application will be simplified.

***Description of the ideal solution***
`tp.create_global_data_node(<Data Node Config>)` should create the Data Node.
The method should raise a dedicated error if the data node config is not global.

***Documentation***
- Add new entry in the release notes
- Add description in the user manual
- Add method to the Ref manual

**Comment by jrobinAV** [comment]
Requires some design discussion
