### ISSUE TITLE
Change default read/write params for generic Data Node to empty lists

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#451]
**Description**
This will simplify the construction of the Generic Data Node.  The below creates an error because _read_fct_params_ is None by default when it should be a list. Making the default _read_fct_params_/_write_fct_params_ as an empty list would avoid any error.

```python
import pandas as pd 
from taipy.config import Config
import taipy as tp


def read_data():
    return "test"

def f(re):
    return re

generic_data_node_cfg = Config.configure_generic_data_node(id="my_data_node",
                                                           read_fct=read_data)
output_cfg = Config.configure_data_node(id="output", storage_type="pickle")
t_cfg = Config.configure_task(id="t",
                              input=generic_data_node_cfg,
                              output=output_cfg,
                              function=f)
pipeline_cfg = Config.configure_pipeline(id="p", task_configs=[t_cfg])


tp.Core().run()
pip= tp.create_pipeline(pipeline_cfg)
pip.submit()
print(pip.output.read())
```

Error message:
```
[2023-01-27 15:48:51,940][Taipy][ERROR]  1 errors occurred during execution of job JOB_t\data_node.py", line 306, in read_or_raise
    return self._read()
  File "C:\Users\jacta\AppData\Local\R-MINI~1\envs\dev\lib\site-packages\taipy\core\data\generic.py", line 106, in _read
    return read_fct(*self.properties[self._READ_FUNCTION_PARAMS_PROPERTY])
TypeError: __main__.read_data() argument after * must be an iterable, not NoneType      
```

**Comment by toan-quach** [comment]
@FlorianJacta @jrobinAV 
I just ran the code again and noticed that it failed at `generic_data_node_cfg = Config.configure_generic_data_node(id="my_data_node", read_fct=read_data)` with missing `write_fct` parameter, I'll add the error message below. This is not related to the issue that you raised for this ticket but I believe it's still crucial to make sure we have the same output or understanding of it! Can you confirm this problem? Or let me know which version you're running so I have a look. Thanks! Also can we confirm if this is a desired behavior or not? Or should the `write_fct` and `read_fct` be optional parameters?

Error message:
```
generic_data_node_cfg = Config.configure_generic_data_node(id="my_data_node", read_fct=read_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: _configure_generic() missing 1 required positional argument: 'write_fct'
```

**Comment by trgiangdo** [comment]
This is due to the recent refactor of `Config.configure_data_node()`.

You will get the same behavior with `Config.configure_generic_data_node()` (on both 2.1 and develop), since `write_fct` and `read_fct` are required.

**Comment by toan-quach** [comment]
Hmmm I understand, but then the question is still, is it a desired behavior? Since a generic dn can be used for only reading or writing as well which may mean the user not needing to provide one of the functions.

**Comment by FlorianJacta** [comment]
I agree with you @toan-quach. The user shouldn't create unnecessary functions to make a Data Node work. However, it asks the question of what we do to handle errors. What do we log when a user tries to write a generic Data Node when he didn't provide one and so on?

**Comment by jrobinAV** [comment]
I agree. This is not great. The `read_fct` and `write_fct` attributes should not be required. Did we change this recently or they were already mandatory before ?

**Comment by toan-quach** [comment]
@FlorianJacta @jrobinAV @trgiangdo 
To answer Florian, I think we can log an error with a simple message saying that no write_fct was ever provided. And to answer Jean-robin, previously, we did specify that read_fct and write_fct are mandatory but we never enforced this. By this I meant we did say read_fct and write_fct as required by naming the variable in data_node_config.py "_REQUIRED_READ_FUNCTION_GENERIC_PROPERTY" and "_REQUIRED_WRITE_FUNCTION_GENERIC_PROPERTY" while still allowing None as the default value. As Giang said earlier, in the most recent refactoring, we removed this None value as the default causing the problem. I proposed that we fix this by reintroducing None as the default value (this might create a situation where a generic dn doesn't have both read and write function but it's not a big issue to me as it's more on the user's side, we should log a warning on the missing read and write function and I think that'd be enough). What do you think?

**Comment by toan-quach** [comment]
@FlorianJacta @jrobinAV @trgiangdo 
To answer Florian, I think we can log an error with a simple message saying that no write_fct was ever provided. And to answer Jean-robin, previously, we did specify that read_fct and write_fct are mandatory but we never enforced this. By this I meant we did say read_fct and write_fct as required by naming the variable in data_node_config.py "_REQUIRED_READ_FUNCTION_GENERIC_PROPERTY" and "_REQUIRED_WRITE_FUNCTION_GENERIC_PROPERTY" while still allowing None as the default value. As Giang said earlier, in the most recent refactoring, we removed this None value as the default causing the problem. I proposed that we fix this by reintroducing None as the default value (this might create a situation where a generic dn doesn't have both read and write function but it's not a big issue to me as it's more on the user's side, we should log a warning on the missing read and write function and I think that'd be enough). What do you think?

**Comment by FlorianJacta** [comment]
Good for me!

**Comment by trgiangdo** [comment]
Agree. Also, @toan-quach maybe "_REQUIRED_READ_FUNCTION_GENERIC_PROPERTY" and "_REQUIRED_WRITE_FUNCTION_GENERIC_PROPERTY" can become "_OPTIONAL...".

Then we can update the DataNodeChecker to check if both read/write functions are not provided, then throw an error. This should be clarified in the doc too.

**Comment by toan-quach** [comment]
What Giang said raised a very good point. Should we consider, in the case where the user doesn't provide either read_fct or write_fct, should we log a warning or log an error? In this scenario, it will create a "useless" dn that isn't capable of reading or writing and will raise an error (MissingReadFunction or MissingWriteFunction) if we try to read/write it. Based on this argument, I believe we should log an error when no read or write function is provided. Do you agree with it? @FlorianJacta @jrobinAV

**Comment by FlorianJacta** [comment]
I don't see the point of creating a generic Data Node without any read_fct and write_fct. I guess it should raise an error.

**Comment by toan-quach** [comment]
Alright sounds good to me! Regarding the original topic of this ticket, we don't have a default value for read/write params. What we did was asked the user to input the params in the form of a list so we can expand them when calling the function using *, this accidentally created a problem, if the user passes a value that's not an iterable, it will return an error as you raised @FlorianJacta . What we can improve is, if the value the user provides is not an iterable, we will wrap it in a list to avoid this problem, we also should improve the documentation for generic datanode regarding this :D

**Comment by toan-quach** [comment]
Also, to make it clearer, should we rename read_fct_params and write_fct_params to read_fct_args and write_fct_args, we can also expand this by adding read_fct_kwargs and write_fct_kwargs. 
Would love to hear your opinion @FlorianJacta @jrobinAV

**Comment by FlorianJacta** [comment]
It is a great idea to wrap it, but the original problem was that an error would be raised if you didn't provide anything in the (read/write)_fct_params. The default value of these parameters should be a list or something like this. For the renaming, it might be a good suggestion. I don't have a strong opinion on it.

**Comment by toan-quach** [comment]
I agree, I'll keep that in mind :D thanks Florian

**Comment by toan-quach** [comment]
@FlorianJacta 
Hi again,
It seems that I couldn't replicate your error. I made some test before I made the changes and wasn't able to reproduce the problem, I also had a look at the code, if the value of the read/write params is None, it will not pass the params. I was able to reproduce the message only when the value is integer or any iterable value but not None. Can you check which version you're running on? Regardless, I have made several adjustments and now we will wrap non-iterable value with a list to avoid system error should anyone want to create a DN without using the config. Meanwhile, the config checker will still log an error saying that the param for read/write fct should be either a list or a tuple and produce, if not, it will raise systemexiterror.

**Comment by jrobinAV** [comment]
@toan-quach Can we move the issue to Done?

**Comment by toan-quach** [comment]
yep done
