### ISSUE TITLE
Rename DefaultCustomDocument to DefaultDocument

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#458]
- [ ] Change the name of the class and module
- [ ] Change in Ref man
- [ ] Change in the user manual

**Comment by toan-quach** [comment]
@jrobinAV 
I think we can be more specific with the name, something like MongoDefaultDocument would be better IMO as I think DefaultCustomDocument is only exposed for MongoDB DN, no?

**Comment by toan-quach** [comment]
@jrobinAV 
I think we can be more specific with the name, something like MongoDefaultDocument would be better IMO as I think DefaultCustomDocument is only exposed for MongoDB DN, no?

**Comment by trgiangdo** [comment]
I think you got a point Toan, it's only used by MongoCollection DN anyway. I'm down.

**Comment by toan-quach** [comment]
@trgiangdo @jrobinAV 
also does it make sense to relocate the class to under `mongo.py`? I noticed that it's in `common/default_custom_document.py`

**Comment by trgiangdo** [comment]
I don't have strong opinion about where it should be tbh.
It's usually better to split classes into different files, but in this case it's may not.

**Comment by jrobinAV** [comment]
1. I believe it is in the common package for legacy reasons, either because of the first item or because it is a class exposed in the config. I don't remember.

2. I am surprised it s only used by Mongo. I thought it was used by Json as well.
But in Json, we are using a decoder. Would it make sense to group them under the same name for all Document based data nodes, exactly like we grouped exposed types for tabular data nodes? If not, I agree we should rename it and move it.

**Comment by toan-quach** [comment]
That's interesting. I didn't know it can potentially be used by Json as well. I can have a look at this and get back to this later :D

**Comment by jrobinAV** [comment]
No. it s not used by Json. I was mistaken thinking that.

**Comment by toan-quach** [comment]
Kay then it looks like we can rename and move the file to under mongo.py :D regarding your first point being a common class, I found it being used by the config, but the usage is simple and I think there won't be a problem moving it to mongo.py
