### ISSUE TITLE
Rename `configure_default_data_node()` to `set_default_data_node()`

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#470]
**Description**

- [ ] Rename `configure_default_data_node()` to `set_default_data_node()`. Similar with `configure_default_task()`, `configure_default_pipeline()`, ...

This is a breaking change or not if we just deprecate the method.

**Documentation**
It must be documented in:
- The reference manual
- The user manual should have sections (in data-node-config, task-config, ...) to explain what is the method used for?
- The release notes page

**Comment by trgiangdo** [comment]
@jrobinAV  What do you think about deprecating the methods in 2.3.2 (or whatever the next hotfix is), then rename it completely in 3.0?

**Comment by jrobinAV** [comment]
Yes makes sense to me.
