### ISSUE TITLE
Remove deprecated attributes and methods

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#479]
- Must be done in a major release (3.0.0).

- Must be well documented in release notes

**Comment by trgiangdo** [comment]
Since the methods are deprecated before, do we need to specify that in the doc?

**Comment by jrobinAV** [comment]
> Since the methods are deprecated before, do we need to specify that in the doc?

The methods should not be documented anymore, but in the release notes we should have an entry listing them.
