### ISSUE TITLE
Add the ability to rename a version of the Taipy application

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#481]
***Description***

The idea is to add an option on the CLI to allow renaming a version name.

`--rename` takes 2 arguments, the first one is the old version name, and the second one is the new version name.

```bash
$ python3 main.py --list-version
Version number                         Mode                   Creation date       
1.0                                    Experiment (latest)    2023-02-02 11:42:31 
fcf1ebd2-9d45-4e32-b48f-18ff870c3438   Development            2023-02-02 11:42:05 


$ python3 main.py --rename 1.0 0.1
Successfully rename version 1.0 to version 0.1


$ python3 main.py --list-version
Version number                         Mode                   Creation date       
0.1                                    Experiment (latest)    2023-02-02 11:42:31 
fcf1ebd2-9d45-4e32-b48f-18ff870c3438   Development            2023-02-02 11:42:05
```

TODO:
- [ ] Add the rename functionality to the versioning system (on all repositories).
- [ ] Update relnotes

**Comment by jrobinAV** [comment]
We cannot capture an empty string on CLI. We could use a keyword like `no-version`.

```
$ python3 main.py --rename no-version 1.0
```

**Comment by trgiangdo** [comment]
On MacOS, the CLI can actually capture an empty string.
For example
```
$ python3 main.py --rename '' 1.0
```
and the `args.rename` is actually `['', '1.0']`. The same for `""`.

However, we need to test if this is a consistent behavior across different types of terminal.

**Comment by trgiangdo** [comment]
Legacy version migration should not be done by the renaming option (since it requires to load the Config, and to check for compatibility with legacy entities as well).
