### ISSUE TITLE
Implementation data migration API on production and experiment mode

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#482]
**What would that feature address**

When there is multiple version of a Taipy core application on production environment, when there is major conflict, it is not possible to run (or get) old entities.

***Description of the ideal solution***

1. On experiment mode
When the user wants to update an existing experiment version:
- Without the `--force` option:
  &rarr; Prompt the ConfigComparator output
  &rarr; Prompt a suggestion: “Add a new  experiment version or use the `--force` option to override the Config of the current version”.
- With the `--force` option:
  &rarr; Overwrite the Config.
  &rarr; The `--force` option does not migrate entities:
  &rarr; If the user wants to migrate entities of an experiment, then he/she should delete the version and create a new one with the same name (which is a bit restrictive). This should be clarified on the doc.

There is no support for migrating experiment entities at the moment. Because the purpose of an experiment version is to store a stable version of the application, and if the Config is forced to update, then it is not really stable.
 
2. On production mode
- When the user wants to update an existing production version:
  - Without the `--force` option:
  &rarr; Prompt the ConfigComparator output
  &rarr; Prompt there are migration function(s) that also need to be updated.
  &rarr; Prompt suggestions: “Add a new  production version with the migration function or Use the `--force` option to override the current version, and don’t forget to update the migration functions to this version as well”.
  - With the `--force` option:
  &rarr; Only force update the Config on the current version, not the older ones.
  &rarr; Migrate entities of the older on the fly (when there are conflicts) using the migration method provided by the users.

- When the user pushes a new production version:
  - Ignore the `--force` option.
  - We only need to apply the ConfigComparator with the latest production version before this.
We check if there is any migration function or not; if there is not, then print out a Warning.

***Caveats***
 
With `job_executionmode="standalone"`, we need to make sure that the migration function is applied to entities on subprocess as well.

**Comment by jrobinAV** [comment]
@trgiangdo, Can you set up a meeting this week to discuss the issue and try to unblock it?
