### ISSUE TITLE
Implement an API to add migration functions and a checker for migration functions

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#489]
**Description**

- [x] Implement `Config.add_migration_function` API
```python
Config.set_version_migration(
    source_version="1.0",
    target_version="2.0",
    data_node_migration_fct=...,
    task_migration_fct=...,
    pipeline_migration_fct=...,
    scenario_migration_fct=...,
)
```
to add migration functions to the Config singleton.

- [x] Implement a `MigrationFunctionChecker` to check if there is any migration function has been assigned for a specific "source_version"&rarr;"target_version" migration.

**Comment by jrobinAV** [comment]
I would not implement the auto=True/False for now.
I believe we can have a first version without the automatic migration.
ANd once we are ready, we will open the auto parameter. What do you think ?

**Comment by trgiangdo** [comment]
Agree. The `auto` parameter will be added with the automatic migration feature later.
