### ISSUE TITLE
FSRepository: End-to-end testing

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#498]
- [ ] Move tests/test_complex_application.py from taipy-core to taipy-integration-testing repository
- [x] Check with the CS team use cases/projects that can be used to validate the changes on Children classes
- [x] Add previous use cases to the taipy-integration-testing repository

**Comment by toan-quach** [comment]
Some links the CS team provided for this ticket:
https://github.com/Avaiga/demo-covid-dashboard
https://github.com/Avaiga/demo-churn-classification
https://github.com/Avaiga/demo-production-planning

**Comment by toan-quach** [comment]
Some links the CS team provided for this ticket:
https://github.com/Avaiga/demo-covid-dashboard
https://github.com/Avaiga/demo-churn-classification
https://github.com/Avaiga/demo-production-planning
