### ISSUE TITLE
BUG-Config doesn't expose entity access methods

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-core#550]
**Description**
Config tooltip does not expose access methods like described in the [doc](https://docs.taipy.io/en/latest/manuals/reference/taipy.config.Config/#taipy.config.config.Config.scenarios)

**How to reproduce**
In the IDE, import Config from taipy
try to auto-complete Config.scenarios ... 

**Expected behavior**
Allow access to Config methods

**Runtime environment**
 - Taipy version: dev

**Comment by jrobinAV** [comment]
The estimate of 2 is a timebox.
