### ISSUE TITLE
BUG-Choosing a function for a Task in Studio when a venv is in the CWD freezes VSCode to death

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-core#572]
**Description**
I use Python venv native module to create virtual environments for my projects instead of anaconda (like a lot of people)

This module spawns a virtual environment in my current working directory:
![image](https://github.com/Avaiga/taipy-core/assets/62465003/41f3d2d2-e8a6-4615-989b-d1bd3cd8f5e1)

When I choose a function for a Task Node:
![image](https://github.com/Avaiga/taipy-core/assets/62465003/b82710f9-d181-46bf-8e81-3e8161133727)

Taipy Core will analyze every Python File in my current working directory which means analyze the thousands of Python files in my virtual environment.

This consumes all of my memory and freezes Taipy Studio to death:
![image](https://github.com/Avaiga/taipy-core/assets/62465003/b7d02821-3be7-4d46-a9bd-e82e52554aac)
![image](https://github.com/Avaiga/taipy-core/assets/62465003/f9a2fa6f-fea8-4244-b909-1166627cb671)

**How to reproduce**

- Create a virtual environment in your current working directory using `python -m venv venv`
- Activate the environment and install a few libraries in it using pip
- Create a Taipy Studio config
- Create a Task Node
- Choose a function for that Task Node

**Expected behavior**
The same way we use .gitignore to ignore non-relevant files when comparing with a repo, there should be a way to ignore specific files or folders when Taipy Studio analyzes the current working directory.

**Runtime environment**
 - Taipy version: 2.2.0
 - Taipy Studio version: 1.0.0
 - OS: Windows

**Comment by jrobinAV** [comment]
Hello, 

That is not a taipy-core issue. That is for taipy-studio-config

**Comment by jrobinAV** [comment]
Issue moved to [Avaiga/taipy-studio-config #52](https://github.com/Avaiga/taipy-studio-config/issues/52) via [**Zenhub**](https://www.zenhub.com/)
