### ISSUE TITLE
BUG-Defining read_fct_params on a Generic Data Node does not work according to Docs

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-core#573]
**Description**
When defining the read_fct_params for a Generic Data Node in Taipy Core:

This works:
![image](https://github.com/Avaiga/taipy-core/assets/62465003/8715bc1b-1ded-4354-9be7-578ad2888101)

But this doesnt:
![image](https://github.com/Avaiga/taipy-core/assets/62465003/e763e0c6-73e5-4aad-a7bc-9debf7b46c1d)
with error ```[2023-05-12 12:36:47,172][Taipy][ERROR] Issue(level='ERROR', field='read_fct_params', value='data/yelp_review_repaired.csv', message='`read_fct_params` field of DataNode `review_data` must be populated with a Tuple value.', tag='_DataNodeConfigChecker')```

And this doesnt despite being the format defined in the [docs](https://docs.taipy.io/en/develop/manuals/core/config/data-node-config/#generic):
![image](https://github.com/Avaiga/taipy-core/assets/62465003/8f2356ea-0cd5-4d14-985b-dff37907a619)
with error ```[2023-05-12 12:39:14,051][Taipy][ERROR] Issue(level='ERROR', field='read_fct_params', value=['data/yelp_review_repaired.csv'], message='`read_fct_params` field of DataNode `review_data` must be populated with a Tuple value.', tag='_DataNodeConfigChecker')```

**How to reproduce**

```python
    Config.configure_generic_data_node(
    "review_data",
    read_fct=get_data,
    read_fct_params=[REVIEW_PATH],
    write_fct=None,
    write_fct_params=(),
)
```

**Expected behavior**

read_fct_params should either accept List objects as defined in the docs or should accept single-item tuple (and the documention needs to be updated)

**Runtime environment**
Please specify relevant indications.
 - Taipy version: 2.2.0
 - OS: Windows
and any other relevant information.

**Comment by trgiangdo** [comment]
Hi @AlexandreSajus, `read_fct_params=[REVIEW_PATH]` should not work and we need to update the documentation.
However, `read_fct_params=(REVIEW_PATH)` should work.

Can you also provide the value of `REVIEW_PATH`?

**Comment by AlexandreSajus** [comment]
> Hi @AlexandreSajus, `read_fct_params=[REVIEW_PATH]` should not work and we need to update the documentation. However, `read_fct_params=(REVIEW_PATH)` should work.
> 
> Can you also provide the value of `REVIEW_PATH`?

Sure:
```python
REVIEW_PATH = "data/yelp_review_repaired.csv"
```

**Comment by trgiangdo** [comment]
Thank you @AlexandreSajus. I found the issue and I will discuss with the back-end team to resolve this asap.

**Comment by AlexandreSajus** [comment]
Thanks!

**Comment by trgiangdo** [comment]
Hi @AlexandreSajus, regarding the problem of `GenericDataNode`, indeed it is a documentation problem. We will update the doc asap. Thank you.

And FYI, starting from Taipy 2.3 (which is scheduled in June), `read_fct_params` and `write_fct_params` are renamed to `read_fct_args` and `write_fct_args`, and they must be List (to avoid the problem with tuple as you stated).
