### ISSUE TITLE
pandas 2.0 support

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-core#575]
**Description**

I installed the latest version of taipy via pip and it removed pandas 2.0.1 from my environment, and installed 1.5.3 instead.

Is there any reason you're not supporting pandas 2.0.1?

**Comment by jrobinAV** [comment]
Hello @Dr-Irv,

There is no reason. We had no time to update it before the previous release. We will definitely update it for the next release planned for mid-June.

Thx !

**Comment by jrobinAV** [comment]
Note for the assignees : 
- Ensure to make it consistent with taipy-gui
- Don't forget to add the change to the release notes

**Comment by jrobinAV** [comment]
Hi,

taipy-core depends on modin that does not support pandas 2.x yet. 
We are waiting for modin ticket [#5936](https://github.com/modin-project/modin/issues/5936) to be done first.
A [PR](https://github.com/modin-project/modin/pull/5995) is opened on modin project.

**Comment by joaoandre-avaiga** [comment]
@jrobinAV The PR on Modin was merged yesterday, also a release 0.22.1 was made, although it looks like it doesn't include pandas 2.0 support just yet. Maybe by the next sprint this will be unblocked.

**Comment by jrobinAV** [comment]
0.22.1 is a patch version. I guess they only include hotfixes. It will probably be out in the next minor version 0.23.0. I hope it will be before our own release taipy 2.3.0.

**Comment by jrobinAV** [comment]
0.22.2 has been released without the pandas 2.0 support. However a release candidate ([0.23.0.rc0](https://github.com/modin-project/modin/releases/tag/0.23.0rc0)) has been published supporting pandas 2.0.
The actual release should be out in a few a days.

**Comment by jrobinAV** [comment]
[Version 0.23.0](https://github.com/modin-project/modin/releases/tag/0.23.0) of modin has been released today supporting pandas 2.0 but not 1.5 anymore.
