### ISSUE TITLE
BUG-DataNode with Postgresql and url encoded strings messes up escaping

### ISSUE THREAD

**Issue by s-wel** [Avaiga/taipy-core#626]
**Description**
I added url encoded strings in a PostgreSQL database that I access via a DataNode. After this change, taipy could no longer query the data. After investigating the node config, I realized that the escaping of the query string does not seem to work correct (I think).

The following part of the sql query string in the node configuration illustrates the issue. I provided the sender_id "user%20-%20r-u-YG_5MKYTX-3l1ocw" to the node config via a multi-line f string. These are my test results. I am not sure how to debug this further.

Provided: `where sender_id = "user%20-%20r-u-YG_5MKYTX-3l1ocw"`
Received: `where sender_id = \"user%20-%20r-u-YG_5MKYTX-3l1ocw\"\n`

Provided: `where sender_id = "stefan\%20-\%20r-u-YG_5MKYTX-3l1ocw"`
Received:  `where sender_id = \"stefan\\%20-\\%20r-u-YG_5MKYTX-3l1ocw\"\n`

Provided: `where sender_id = 'user%20-%20r-u-YG_5MKYTX-3l1ocw'`
Received: `where sender_id = 'user%20-%20r-u-YG_5MKYTX-3l1ocw'\n`

Provided: `where sender_id = 'user\%20-\%20r-u-YG_5MKYTX-3l1ocw'`
Received: `where sender_id = 'user\\%20-\\%20r-u-YG_5MKYTX-3l1ocw'\n`

**Expected behavior**
I expect that the query works when the query string is url encoded.

**Runtime environment**
Please specify relevant indications.
 - Taipy version: 2.2.0
 - OS: WSL (Ubuntu)
 - PostgreSQL 11.12
and any other relevant information.

**Comment by FlorianJacta** [comment]
Thank you for your issue! We are currently investigating it. We will come back to you as soon as possible.

**Comment by trgiangdo** [comment]
Hello @s-wel, we are investigating this bug but we can not reproduce it yet.

Can you help us by providing a minimal code and some instructions so we can reproduce the problem?

**Comment by s-wel** [comment]
I agree that it is hard to reproduce. Maybe it is an edge case. I cannot provide a snippet now that reproduces the behavior so I suggest closing the issue.

**Comment by jrobinAV** [comment]
Hi, 

Thank you, @s-wel.

Do not hesitate to open a new issue if the problem appears again.
