### ISSUE TITLE
BUG- tp.run raise an error

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#635]
**Description**
Using `tp.run()` raises an error.

```
Traceback (most recent call last):
  File "C:\....py", line 3, in <module>
    tp.run(tp.Core(), tp.Gui("test"))
  File "C:\Users\jacta\.conda\envs\2.3\lib\site-packages\taipy\_run.py", line 45, in _run
    from taipy.core._version._cli._core_cli import _CoreCLI
ModuleNotFoundError: No module named 'taipy.core._version._cli._core_cli'
```

**How to reproduce**
```python
import taipy as tp

tp.run(tp.Core(), tp.Gui("test"))
```

**Expected behavior**
Core service should run and my Taipy webpage should work.

**Runtime environment**
Please specify relevant indications.
 - Taipy version: 2.3.dev2

**Comment by trgiangdo** [comment]
@FlorianJacta we have release 2.3.dev3 on all packages. Can you reinstall and try again?
