### ISSUE TITLE
Support for SQL Alchemy 2.0

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-core#646]
We are integrating an application that we wrote using `sqlalchemy` 2.0.  But taipy is based on `sqlalchemy` 1.4.x .   So we had to convert a bunch of our `sqlalchemy` code to use `taipy`

is there a reason you can't support `sqlalchemy` 2.0?

**Comment by jrobinAV** [comment]
Hello, 

Thank you for the feedback. We are looking at the impacts of upgrading to sqlalchemy 2.0. 
We'll let you know the results and a target release version.

Thx,
