### ISSUE TITLE
ensure methods have the right visibility on converters

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#662]
Some methods are hidden but could be private. We need to verify:
_deserialize_sql_dn_model_properties, _serialize_edits, and many more

**Comment by trgiangdo** [comment]
In `src/taipy/core/data/_data_converter.py`:
- `_serialize_sql_dn_properties()` should be private
- `_serialize_mongo_collection_dn_model_properties()` should be private
- `_serialize_edits()` should be private
- `_deserialize_sql_dn_model_properties()` should be private
- `_deserialize_sql_dn_model_properties` should be private
- `_deserialize_edits` should be private

In `src/taipy/core/data/_abstract_tabular.py`:
- `_serialize_exposed_type()` is not used anywhere
- `_deserialize_exposed_type()` is not used anywhere

In `src/taipy/core/data/data_node.py`:
- `_serialize_datanode_properties()` should be removed
- `_deserialize_datanode_model_properties()` should be removed

In `src/taipy/core/job/_job_converter.py` and `src/taipy/core/job/job.py`:
- `_serialize_subscribers()` should be private

**Comment by jrobinAV** [comment]
Sounds good. I suspect the unused methods were used before the repository refactoring. @joaoandre Do you know if I am right?
