### ISSUE TITLE
Add new API to know if a Data Node is up to date

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#668]
### What problem does this feature solve?
The feature aims to provide a solution for determining whether a Data Node is up-to-date. This functionality would simplify the management and utilization of Data Nodes within a Taipy application.

When called, `<Data Node>.is_up_to_date` would return True if all preceding Data Nodes in the graph have not been modified since the last execution.
If any of the preceding Data Nodes have been written or modified, `<Data Node>.is_up_to_date` would return False.

The revised implementation would involve renaming the existing function, `<Data Node>.is_up_to_date`, to `<Data Node>.is_valid`.

**Comment by jrobinAV** [comment]
For end users, it will be difficult to remember the difference between `is_up_to_date` `from is_valid`.
What about replacing `is_up_to_date` by `has_new_upstream_data` ?

**Comment by toan-quach** [comment]
Requirement:

- [ ] get all previous preceding data nodes of the targeted dn (based on the scenario it belongs to)
- [ ] check if any of the preceding data node has its _last_edit_date larger than its children nodes
- [ ] check step 2 for all parent scenarios
- [ ] add unit tests

**Comment by toan-quach** [comment]
@FlorianJacta @jrobinAV 
So to conclude:
We will have 2 functions:
- `is_valid`: as Florian raised, it will be used to check if the dn is still valid (expired or not)
- `is_up_to_date`: to check if preceding/ancestor DNS have been updated (`last_edit_date` was changed and it was after the selected dn). This check will happen on all preceding datanodes that share the same scenario with the selected dn

**Comment by jrobinAV** [comment]
What I understand is that the is_up_to_date method should check both:
- All ancestors have not been written after the current DN.
- The current DN is valid regarding the validity period.

**Comment by toan-quach** [comment]
@jrobinAV yep I think you're right!
