### ISSUE TITLE
add new APIs on submittable entities

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#672]
- [x] Rename submittable._get_inputs to make it public (get_inputs). It returns the set of input data nodes.
- [x] Add submittable.get_outputs. It should return the set of output data nodes.
- [x] Add submittable.get_intermediates. It should return the set of data nodes that are not an input nor an output. 
- [x] Add submittable.is_ready_to_run.
```
def is_ready_to_run(self):
    return all([d.is_ready_for_reading for d in submittable.get_inputs()])
```
- [x] Add submittable.execution_in_progress method that returns the set (eventually empty) of data nodes of the submittable that are in progress.
- [x] Add documentation (user man and ref man)
- [x] Add release notes

**Comment by toan-quach** [comment]
@jrobinAV 
For `submittable.execution_in_progress`, I don't think this will be feasible at least in development mode. In standalone mode, it should be doable. What do you think?

**Comment by jrobinAV** [comment]
Since the development mode is synchronous, when a user calls `submittable.execution_in_progress`, no data node will be in progress. You are right. Maybe there will be some specific cases where the application stops during an execution. When it restarts, some data nodes could be in progress while no job is running. It s kind of a pathological case.

In any case, I believe we can implement it regardless of the execution mode. It should work for all cases.

**Comment by toan-quach** [comment]
I believe you're right!
