### ISSUE TITLE
Rename pipeline to sequence

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#684]
Rename pipeline to sequence in :
- module
- class attributes
- internal variables
- methods
- repository names, 
- unit tests names
- taipy API (keeping deprecated the exposed API containing pipeline name)
- notifications
- docstrings for ref manual

To keep compatibility, do not rename (not yet?):
- Pipeline Object itself.
- Folder name in .data

**Comment by toan-quach** [comment]
@jrobinAV 
Some recommendations aside from sequence:
- Task groups
- Task subsets
- Task subgroups
- Task subdivisions
- Task fragments

**Comment by toan-quach** [comment]
- [x] Config
- [x] Core
- [x] Rest
- [x] Enterprise
- [ ] Integration
