### ISSUE TITLE
BUG-Write of Excel data node not working properly

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#700]
**Description**
An error occurs when trying to read a Excel Data Node with a particular sheet name that has been written by Taipy.

```
  File "...\site-packages\pandas\io\excel\_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "...\site-packages\pandas\io\excel\_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'one' not found
```

**How to reproduce**

```python
import taipy as tp 

in_ = tp.Config.configure_data_node(id="input", default_data={"x": [1, 2], "y": [3, 4]})

out = tp.Config.configure_excel_data_node(id="output", sheet_name="one")

def id(i):
    return i 

t = tp.Config.configure_task(id="task", input=[in_], function=id, output=[out])

s_cfg = tp.Config.configure_scenario_from_tasks(id="scenario", task_configs=[t])

tp.Core().run()

s = tp.create_scenario(s_cfg)
s.submit()

print(s.output.read())

```

**Expected behavior**
The above code should work. The Excel file should contain the sheet.

**Runtime environment**
Taipy 2.3.1

**Comment by toan-quach** [comment]
@jrobinAV 
should we also include the fix for this in 2.3?

**Comment by jrobinAV** [comment]
Yes, we should merge the fix into 3 branches:
- release/2.3
- dev/2.4
- develop

**Comment by jrobinAV** [comment]
Can we move the ticket to done?
@FlorianJacta did you test it?

**Comment by FlorianJacta** [comment]
Not working on 2.4 with the same error

**Comment by jrobinAV** [comment]
Hum 🤔. 
Thank you. 
We are going to check that.

**Comment by toan-quach** [comment]
@FlorianJacta I just tested using branch `release/2.4` on Github (the fix hasn't been published yet so please use branch realease/2.4 instead) 

Here is my output:
![image](https://github.com/Avaiga/taipy-core/assets/93168955/1ba4cbb1-53dd-41e6-8240-441ae948723e)

Here is the code I used: 
```
import taipy as tp 

in_ = tp.Config.configure_data_node(id="input", default_data={"x": [1, 2], "y": [3, 4]})

out = tp.Config.configure_excel_data_node(id="output", sheet_name="one")

def id(i):
    return i

t = tp.Config.configure_task(id="task", input=[in_], function=id, output=[out])

s_cfg = tp.Config.configure_scenario_from_tasks(id="scenario", task_configs=[t])

tp.Core().run()

s = tp.create_scenario(s_cfg)
s.submit()

print(s.output.read())
```

**Comment by FlorianJacta** [comment]
True, working on develop and release/2.4. Everything is fine, sorry about that!

**Comment by toan-quach** [comment]
no worry!!!
