### ISSUE TITLE
implement data_node._get_user_properties(*key_to_add) method API

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#701]
For DataNodeviewer core visual element [(specifications)](https://docs.google.com/document/d/1L5_OPxiAZX9ZU9d6yomMzDZV-Bpv6bA-SW_GRC7n8Do/edit#heading=h.rjc1l3svrrf1), a new API should be opened.

It consists in building dynamically and returning the property list containing only the custom properties created by the user. The Taipy internal properties must be filtered out.

Eventually, the caller can provide a list of property keys NOT to filter out.

``` python
def (self, *list_of_properties_to_keep): -> Dict
    pass
```

**Comment by trgiangdo** [comment]
For now, the implementation of `DataNode._get_user_properties()` API accepts no parameter, and return only the custom properties of the user.

If it accepts `*list_of_properties_to_keep` parameter, what will it return?
- The properties in the list + all custom properties.
- Only the properties in the list.

**Comment by trgiangdo** [comment]
We decided to not add any parameter to the API at the moment. We can do that in the future if necessary
