### ISSUE TITLE
Append performance data from taipy-integration-testing instead of replacing the file

### ISSUE THREAD

**Issue by joaoandre-avaiga** [Avaiga/taipy-core#729]
When running the perfomance benchmark action, we generate csv files with the performance data. Currently, the files are replaced every time the action is run. We would like to replace the behavior and only append the data into a file on azure blob storage, so it would be possible to track the performance over time.

**Comment by trgiangdo** [comment]
https://docs.google.com/document/d/1tyeOaKDzP5PDrRdgBC5y1SOnQGe8f0Nf0BaE4p7m38I

**Comment by toan-quach** [comment]
@joaoandre-avaiga I believe for this ticket, we only need to add the report file when trigger the benchmark. In particular:
`ScenarioPerfBenchmark(github_sha: str, entity_counts: list[int] = None, report_path: str = None)` has attribute `report_path` set to None. We just need to provide a report path to initialization and this ticket will be solved.

**Comment by toan-quach** [comment]
@joaoandre-avaiga after careful investigation, I don't think we need to make any changes, as the code should know to download the current result, append to the file and push it back up. Should we discuss more on this?
