### ISSUE TITLE
Investigate the use of `is_consistent` in Pipeline

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy-core#734]
**Description**
Discuss and investigate the use of `is_consistent` in Pipeline:

- Does a pipeline have to be connected? Or it's okay as long as it's a DAG or DAGs?
- Does the scenario need to have a consistency check function as well? If yes, does it have to be connected or it's okay just being a DAG or DAGs?

At least the graph should be acyclic for both pipeline and scenarios.

**Comment by toan-quach** [comment]
@jrobinAV 
I have added the questions we had during the discussion for this topic in the description.

**Comment by toan-quach** [comment]
@jrobinAV 
I have added the questions we had during the discussion for this topic in the description.

**Comment by toan-quach** [comment]
@jrobinAV 

To conclude from our discussion from before:
- For Sequence, we will check if a Sequence is a "connected DAG", if not, we will raise an error
- For Scenario, we will check if a Scenario is a DAG or not (it can be connected or not connected)

**Comment by jrobinAV** [comment]
we will also check that the DAG is made of Task and Data nodes only and that a task is not linked to other tasks and data node not linked to other data nodes.
