### ISSUE TITLE
Manual data node editing requires a lock mechanism

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#742]
In particular in the data node viewer, when entering in a data edition mode, the end user needs to lock the data node before writing the data so other users cannot enter in the edition mode. The lock should apply to all but himself. He needs to be identified so he can actually write the data. The lock should have an expiration date.

Note: `data_node.edition_in_progress` already exists to let the user know that someone is about to write the data.

Note: The orchestrator can remove the editor lock to overwrite it.

**Copilote sketch of solution**:

```python
    def lock_edit(self, editor_id: Optional[str]):
        """Lock the data node modification.

        Note:
            The data node can be unlocked with the method `(DataNode.)unlock_edit()^`.
        """
        if editor_id:
            if self.edit_in_progress:
                if self.editor_id != editor_id and self.editor_expiration_date > datetime.now():
                    raise EditInProgress(f"Data node {self.id} from config {self.config_id} is being edited by "
                                         f"{self.editor_id}.")
            self.editor_id = editor_id
            self.editor_expiration_date = datetime.now() + timedelta(seconds=self.EDIT_TIMEOUT)
            self.edit_in_progress = True
        else:
            self.edit_in_progress = True

    def unlock_edit(self, editor_id: Optional[str]):
        """Unlocks the data node modification.
        Note:
            The data node can be locked with the method `(DataNode.)lock_edit()^`.
        """
        if self.editor_id and editor_id:
            if elf.editor_id != editor_id and self.editor_expiration_date > datetime.now():
                raise EditInProgress(f"{editor_id} cannot unlock edition of data node  {self.id}. It is being edited by "
                                         f"{self.editor_id}.")
                self.editor_id = None
                self.editor_expiration_date = None
                self.edit_in_progress = False
        else:
            self.editor_id = None
            self.editor_expiration_date = None
            self.edit_in_progress = False
```

**Expected output**:
- [ ] Implement the new lock mechanism adding new attributes to the data node.
- [ ] Implement unit tests
- [ ] Change the reference manual
- [ ] Add a specific paragraphe in the user man data-node-mgt page to explain the whole lock mechanism (`lock_edit`, `unlock_edit`, `edit_in_progress`, `editor_id`, `editor_expiration_date`)
- [ ] Add new entry in release notes

**Comment by FredLL-Avaiga** [comment]
looks good
Should the unlock_edit get an editor_id also ?

**Comment by toan-quach** [comment]
so for lock, if we don't provide editor_id, it will force lock regardless?

**Comment by toan-quach** [comment]
also how much should we set for EDIT_TIMEOUT?

**Comment by jrobinAV** [comment]
> so for lock, if we don't provide editor_id, it will force lock regardless? 

yes

**Comment by jrobinAV** [comment]
> also how much should we set for EDIT_TIMEOUT? 

I would set 30 minutes.
