### ISSUE TITLE
Trigger integration testing when merging taipy-core develop

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#744]
merge on develop triggers performance testing run. it should also trigger integration-testing unit tests

**Comment by toan-quach** [comment]
@jrobinAV I noticed we have already had a scheduled cronjob that will run daily on integration develop branch. So I don't think if this ticket will provide much value? I believe we don't need both features and should keep only one between the 2

**Comment by toan-quach** [comment]
@jrobinAV I noticed we have already had a scheduled cronjob that will run daily on integration develop branch. So I don't think if this ticket will provide much value? I believe we don't need both features and should keep only one between the 2

**Comment by toan-quach** [comment]
- if develop on core is merged, run the integration tests
- after running, if it failed, send email to person that merged the PR on core develop 
- remove the daily actions for integration tests
