### ISSUE TITLE
Improve Dev process: Investigate grouping Core and Rest in the same repo

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#802]

**Comment by trgiangdo** [comment]
Just to clarify, this means taipy-rest will be a part of the taipy-core package, or there will still be 2 separate packages?

**Comment by jrobinAV** [comment]
> Just to clarify, this means taipy-rest will be a part of the taipy-core package, or there will still be 2 separate packages?

This ticket is about investigating the merge of the repos only, keeping two separate packages.

**Comment by joaoandre-avaiga** [comment]
@jrobinAV Should we close this since we are going to group all the repos together?

**Comment by jrobinAV** [comment]
Yep.
